version: '3.8'
services:
    agamotto:
        image: agamotto:latest
        entrypoint: ./scripts/entrypoint.sh
        env_file:
            - .env
        volumes:
            - ./data:/app/project/data
            - ./scripts:/app/scripts
        ports:
            - "5050:5000"